# Generated by Django 4.2.2 on 2024-11-02 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_lesson_unique_title_per_course"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_data",
                    models.DateField(
                        help_text="введите дату платежа", verbose_name="дата платежа"
                    ),
                ),
                (
                    "payment_amount",
                    models.PositiveIntegerField(verbose_name="cумма оплаты"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Наличными"),
                            ("bank_transfer", "Перевод на счет"),
                        ],
                        max_length=20,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="lms.course",
                        verbose_name="оплаченный курс",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="lms.lesson",
                        verbose_name="оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
    ]
