# Generated by Django 4.2.2 on 2024-11-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "платеж", "verbose_name_plural": "платежи"},
        ),
    ]
