# Generated by Django 4.2.2 on 2024-11-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0011_delete_coursepayment"),
        ("users", "0007_payment_created_at_payment_link_payment_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paid_lesson",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="укажите название курса",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="lms.course",
                verbose_name="курс",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="укажите название урока",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="lms.lesson",
                verbose_name="урок",
            ),
        ),
    ]
