# Generated by Django 4.2.2 on 2024-11-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_payment_created_at_remove_payment_paid_course_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_data",
            new_name="payment_date",
        ),
    ]
