# Generated by Django 4.2.2 on 2024-11-11 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0011_delete_coursepayment"),
        ("users", "0009_rename_payment_data_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                help_text="укажите название курса",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="lms.course",
                verbose_name="курс",
            ),
        ),
    ]
