# Generated by Django 4.2.2 on 2024-11-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_payment_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_date",
        ),
    ]
