# Generated by Django 4.2.2 on 2024-11-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличными"), ("card", "Перевод на счет")],
                help_text="укажите способ оплаты",
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
    ]
