# 1
version: '3.9'

services:
  backend:
    container_name: lms-backend
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  db:
    container_name: lms-db
    image: postgres:16.0
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  redis:
    image: redis:latest
    container_name: lms-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    env_file:
      - .env
    restart: unless-stopped
    mem_limit: 256M
    cpus: 0.25

  celery:
    container_name: lms-celery_worker
    build: .
    command: celery -A config worker -l info
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: unless-stopped
    mem_limit: 512M
    cpus: 0.5

  celery-beat:
    container_name: lms-celery_beat
    build: .
    command: celery -A config beat -l info
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: unless-stopped
    mem_limit: 256M
    cpus: 0.25

networks:
  default:

volumes:

  postgres_data:
  static_volume:
