# Generated by Django 4.2.2 on 2024-10-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_video",
            field=models.URLField(
                blank=True,
                help_text="укажите ссылку на видео",
                null=True,
                unique=True,
                verbose_name="ccылка на видео",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="укажите название урока",
                max_length=150,
                null=True,
                verbose_name="название урока",
            ),
        ),
    ]
