# Generated by Django 4.2.2 on 2024-11-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_lesson_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="owner",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="укажите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lms.course",
                verbose_name="курс",
            ),
        ),
    ]
